### ISSUE TITLE
"Install Package" command shows no output, no panel, nothing at all

### ISSUE THREAD

**Issue by ahecht** [wbond/package_control#1293]
When I attempt to run the "Install Package" command, nothing happens. Debug log is below. The problem appears to be an issue connecting to the package repositories, but I'm not having this problem with another computer on the same network with the same settings.

Both machines are running High Sierra, both are on WiFi on the same network, both have OS X Firewall turned off. One one machine, Package Control behaves normally, on the other, nothing.

Debug Log:
```
Package Control: Settings change detected, clearing cache
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Package Control: Exported certificate: Common Name: ANF Global Root CA, Serial Number: G63287510, Email Address: info@anf.es, Organizational Unit: ANF Clase 1 CA, Organization: ANF Autoridad de Certificacion, Locality: Barcelona (see current address at http://www.anf.es/es/address-direccion.html ), State/Province: Barcelona, Country: ES
Package Control: Exported certificate: Organizational Unit: ePKI Root Certification Authority; Organization: Chunghwa Telecom Co., Ltd.; Country: TW
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Buypass Class 2 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: SwissSign Platinum CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G2; Organizational Unit: (c) 2007 thawte, Inc. - For authorized use only; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions RootCA 2011, Organization: Hellenic Academic and Research Institutions Cert. Authority, Country: GR
Package Control: Exported certificate: Common Name: Starfield Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Email Address: acraiz@suscerte.gob.ve, Organizational Unit: Superintendencia de Servicios de Certificacion Electronica, Organization: Sistema Nacional de Certificacion Electronica, State/Province: Distrito Capital, Locality: Caracas, Country: VE, Common Name: Autoridad de Certificacion Raiz del Estado Venezolano
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: Staat der Nederlanden EV Root CA, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: ComSign CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: GeoTrust Global CA, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: CFCA EV ROOT, Organization: China Financial Certification Authority, Country: CN
Package Control: Exported certificate: Common Name: AddTrust Class 1 CA Root, Organizational Unit: AddTrust TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: SwissSign Platinum Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: NetLock Arany (Class Gold) Főtanúsítvány, Organizational Unit: Tanúsítványkiadók (Certification Services), Organization: NetLock Kft., Locality: Budapest, Country: HU
Package Control: Exported certificate: Organizational Unit: certSIGN ROOT CA, Organization: certSIGN, Country: RO
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority - G2, Organizational Unit: (c) 2007 GeoTrust Inc. - For authorized use only, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: TRUST2408 OCES Primary CA, Organization: TRUST2408, Country: DK
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: SwissSign Gold Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: KISA RootCA 1, Organizational Unit: Korea Certification Authority Central, Organization: KISA, Country: KR
Package Control: Exported certificate: Common Name: Buypass Class 3 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Organizational Unit: Trustis FPS Root CA, Organization: Trustis Limited, Country: GB
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Organization: TÜRKTRUST Bilgi İletişim ve Bilişim Güvenliği Hizmetleri A.Ş. (c) Aralık 2007, Locality: Ankara, Country: TR, Common Name: TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı
Package Control: Exported certificate: Email Address: pki@sk.ee, Common Name: EE Certification Centre Root CA, Organization: AS Sertifitseerimiskeskus, Country: EE
Package Control: Exported certificate: Common Name: SwissSign Silver Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - EC1; Organizational Unit: (c) 2012 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: VeriSign Class 1 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Apple Root CA - G3, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: Certigna, Organization: Dhimyotis, Country: FR
Package Control: Exported certificate: Common Name: UTN-USERFirst-Hardware, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Email Address: info@e-szigno.hu, Common Name: Microsec e-Szigno Root CA 2009, Organization: Microsec Ltd., Locality: Budapest, Country: HU
Package Control: Exported certificate: Common Name: VRK Gov. Root CA; Organizational Unit: Varmennepalvelut, Certification Authority Services; Organization: Vaestorekisterikeskus CA; State/Province: Finland; Country: FI
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: TWCA Global Root CA, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: Federal Common Policy CA, Organizational Unit: FPKI, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: thawte Primary Root CA; Organizational Unit: (c) 2006 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Email Address: Info@izenpe.com, Common Name: Izenpe.com, Locality: Avda del Mediterraneo Etorbidea 3 - 01010 Vitoria-Gasteiz, Organization: IZENPE S.A. - CIF A-01337260-RMerc.Vitoria-Gasteiz T1055 F62 S8, Country: ES
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: UTN-USERFirst-Object, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: Actalis Authentication Root CA, Organization: Actalis S.p.A./03358520967, Locality: Milan, Country: IT
Package Control: Exported certificate: Common Name: Swisscom Root CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: TeliaSonera Root CA v1, Organization: TeliaSonera
Package Control: Exported certificate: Common Name: Network Solutions Certificate Authority, Organization: Network Solutions L.L.C., Country: US
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: DigiCert Global Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Autoridad de Certificacion Firmaprofesional CIF A62634068, Country: ES
Package Control: Exported certificate: Common Name: Symantec Class 1 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Atos TrustedRoot 2011, Organization: Atos, Country: DE
Package Control: Exported certificate: Common Name: Apple Root CA, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G2, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: Certum Trusted Network CA, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA1, Organization: SECOM Trust.net, Country: JP
Package Control: Exported certificate: Common Name: IdenTrust Public Sector Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 2, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: Apple Root CA - G2, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: ApplicationCA2 Root, Organizational Unit: GPKI, Organization: Japanese Government, Country: JP
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA2; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: VeriSign Universal Root Certification Authority; Organizational Unit: (c) 2008 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: CA Disig Root R1, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: DigiCert Global Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Gold CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Organizational Unit: Security Communication EV RootCA1; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: Hongkong Post Root CA 1, Organization: Hongkong Post, Country: HK
Package Control: Exported certificate: Common Name: AAA Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: Swisscom Root CA 1, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: AffirmTrust Premium, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Organizational Unit: Starfield Class 2 Certification Authority; Organization: Starfield Technologies, Inc.; Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: DigiCert High Assurance EV Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Visa Information Delivery Root CA, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: COMODO RSA Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G3; Organizational Unit: (c) 2008 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Chambers of Commerce Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: SecureTrust CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: UCA Global Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: Common Policy, Organizational Unit: FBCA, Organization: U.S. Government, Country: us
Package Control: Exported certificate: Common Name: UTN - DATACorp SGC, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: Sonera Class2 CA, Organization: Sonera, Country: FI
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: StartCom Certification Authority G2, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: ComSign Secured CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1042, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1071, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1100, in native
  File "package_control.deps.asn1crypto.core in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1702, in native
  File "package_control.deps.asn1crypto.core in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1672, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/ahecht/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 32: character maps to <undefined>
```

**Comment by ahecht** [comment]
I've also tried with a brand new user (as well as a guest user) on the same machine to eliminate any user keychain issues, same problem. So confusing!

**Comment by mvk** [comment]
I have the same issue with OSX too.
Is it possible the server url of packages index has changed ?

**Comment by mvk** [comment]
I've tried reinstalling `Package Control` itself. this is what I got:
```
>>> 
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority; Organizational Unit: (c) 2006 Entrust, Inc., www.entrust.net/CPS is incorporated by reference; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: TWCA Root Certification Authority, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: QuoVadis Root CA 1 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: DigiCert Trusted Root G4, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Apple Root Certificate Authority; Organizational Unit: Apple Computer Certificate Authority; Organization: Apple Computer, Inc.; Country: US
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Organization: TÜRKTRUST Bilgi İletişim ve Bilişim Güvenliği Hizmetleri A.Ş. (c) Aralık 2007, Locality: Ankara, Country: TR, Common Name: TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: SwissSign Platinum CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: Global Chambersign Root - 2008, Organization: AC Camerfirma S.A., Serial Number: A82743287, Locality: Madrid (see current address at www.camerfirma.com/address), Country: EU
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 EV 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: DST Root CA X4, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: Swisscom Root CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Secure Global CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: Certinomis - Root CA, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: Certigna, Organization: Dhimyotis, Country: FR
Package Control: Exported certificate: Common Name: Visa eCommerce Root, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: COMODO RSA Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: VeriSign Class 1 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Email Address: acraiz@suscerte.gob.ve, Organizational Unit: Superintendencia de Servicios de Certificacion Electronica, Organization: Sistema Nacional de Certificacion Electronica, State/Province: Distrito Capital, Locality: Caracas, Country: VE, Common Name: Autoridad de Certificacion Raiz del Estado Venezolano
Package Control: Exported certificate: Common Name: Starfield Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: NetLock Arany (Class Gold) Főtanúsítvány, Organizational Unit: Tanúsítványkiadók (Certification Services), Organization: NetLock Kft., Locality: Budapest, Country: HU
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GA CA; Organizational Unit: OISTE Foundation Endorsed, Copyright (c) 2005; Organization: WISeKey; Country: CH
Package Control: Exported certificate: Common Name: Echoworx Root CA2, Organizational Unit: Certification Services, Organization: Echoworx Corporation, Locality: Toronto, State/Province: Ontario, Country: CA
Package Control: Exported certificate: Organizational Unit: ePKI Root Certification Authority; Organization: Chunghwa Telecom Co., Ltd.; Country: TW
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G4, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R5
Package Control: Exported certificate: Common Name: Sonera Class2 CA, Organization: Sonera, Country: FI
Package Control: Exported certificate: Common Name: UTN-USERFirst-Network Applications, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: Chambers of Commerce Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: Buypass Class 3 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: SecureTrust CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: Symantec Class 3 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G3, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: Network Solutions Certificate Authority, Organization: Network Solutions L.L.C., Country: US
Package Control: Exported certificate: Common Name: Federal Common Policy CA, Organizational Unit: FPKI, Organization: U.S. Government, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Belgium Root CA2, Country: BE
Package Control: Exported certificate: Email Address: pki@sk.ee, Common Name: EE Certification Centre Root CA, Organization: AS Sertifitseerimiskeskus, Country: EE
Package Control: Exported certificate: Common Name: Apple Root CA - G3, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: SwissSign Silver Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: Class 2 Primary CA, Organization: Certplus, Country: FR
Package Control: Exported certificate: Organizational Unit: Starfield Class 2 Certification Authority; Organization: Starfield Technologies, Inc.; Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Networking, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: UCA Global Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: AffirmTrust Premium ECC, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Organization: Government Root Certification Authority, Country: TW
Package Control: Exported certificate: Email Address: Info@izenpe.com, Common Name: Izenpe.com, Locality: Avda del Mediterraneo Etorbidea 3 - 01010 Vitoria-Gasteiz, Organization: IZENPE S.A. - CIF A-01337260-RMerc.Vitoria-Gasteiz T1055 F62 S8, Country: ES
Package Control: Exported certificate: Common Name: ComSign CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: Symantec Class 2 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: Atos TrustedRoot 2011, Organization: Atos, Country: DE
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - EC1; Organizational Unit: (c) 2012 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Exception in thread Thread-54:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1042, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1071, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1100, in native
  File "package_control.deps.asn1crypto.core in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1702, in native
  File "package_control.deps.asn1crypto.core in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1672, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/maxk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x5e in position 2: character maps to <undefined>

```

**Comment by ahecht** [comment]
@mvk At least for me it seems unlikely to be the server URL since it works fine on another machine on the same network. My guess is it's something to do with the certificates or keychain on that specific machine, but I don't know what to do about it..

**Comment by wbond** [comment]
Please follow these instructions to try out the prerelease version that contains a fix for this issue:

 1. Use the Sublime Text *Preferences* menu and click *Browse Packages…*
 2. Navigate up one folder and then into `Installed Packages/`
 3. Close Sublime Text
 4. Delete the file `Package Control.sublime-package` and leave your Explorer/Finder window open
 5. Download https://packagecontrol.io/prerelease/Package%20Control.sublime-package
 6. Place it in the `Installed Packages/` folder
 7. Start Sublime Text

If you are still having trouble, please post a debug log when using the new version (3.3.1-beta1).

**Comment by bioball** [comment]
Nice! That worked, thanks!

**Comment by mvk** [comment]
@wbond thanks for the quick'n'working fix.
So is it some unicode parsing problem? can you point to the patch ?
Curious /me.

**Comment by mvk** [comment]
@wbond I have noticed a scary `\r` character in the commit: `08e70e75` in the file `package_control/deps/asn1crypto/_inet.py`

**Comment by wbond** [comment]
@mvk The issue is that the Teletex string encoding used in X.509 certificates was underspecified, and OpenSSL seems to encode strings using Latin 1 and place them in that data type rather than using (the more logical) ITU T.61 encoding.

The ASN.1 library I wrote was previously strictly following the intent of the spec. However, the issue seems to not be present for the majority of users. It does appear that OpenVPN uses OpenSSL to generate some certificates and places some bytes in the name that ITU T.61 doesn't utilize, so the Python decode for ITU T.61 was complaining that it didn't know what to do.

ans1crypto 0.23.0 special-cases the X.509 decoder to assume that Teletex strings are Windows 1252 (a superset of ISO 8859-1/Latin 1). This may result in some invalid decodings, but will prevent things from "breaking". Most good crypto software explicitly uses UTF-8 strings in X.509 certificates anyways.

 -
 https://github.com/wbond/package_control/commit/08e70e75200d4e86ee934734a4842f9107c878db
 - https://github.com/wbond/asn1crypto/commit/1ba880ef26e37151e71b9968ba1d29b2573cfd43

**Comment by mvk** [comment]
Good catch! Argh, unicode spec, damn you,  Sharktopus :)

**Comment by wbond** [comment]
@mvk Yes, that whole file was written on, and for, Windows, so it seems it got Windows line endings. Shouldn't really be an issue, but I can get it fixed with the next release of asn1crypto.

**Comment by mfueger** [comment]
This has fixed it for me. Thanks!!

**Comment by welenofsky** [comment]
This worked for me, thanks for the update!

**Comment by ahecht** [comment]
this fixed my issue too, closing

**Comment by ktmcl** [comment]
Hi, I'm still seeing this issue. I tried removing & replacing the file as described above, but no change. Here is my console output using 3.3.1-beta4.

Thanks in advance for any insight!

Package Control: Skipping automatic upgrade, last run at 2019-09-11 10:25:01, next run at 2019-09-11 11:25:01 or after
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.1-beta4
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: ::ffff:50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Package Control: Exported certificate: Common Name: Amazon Root CA 2, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: Apple Root Certificate Authority; Organizational Unit: Apple Computer Certificate Authority; Organization: Apple Computer, Inc.; Country: US
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: SSL.com Root Certification Authority RSA, Organization: SSL Corporation, Locality: Houston, State/Province: Texas, Country: US
Package Control: Exported certificate: Common Name: GTS Root R4, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: Visa Information Delivery Root CA, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: COMODO Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: Amazon Root CA 3, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: VeriSign Universal Root Certification Authority; Organizational Unit: (c) 2008 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority - G3, Organizational Unit: (c) 2008 GeoTrust Inc. - For authorized use only, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: Certplus Root CA G2, Organization: Certplus, Country: FR
Package Control: Exported certificate: Locality: Suzhou, State/Province: Suzhou, Common Name: CNSUZ-B01F02C13-CMP01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CN
Package Control: Exported certificate: Common Name: Certum Trusted Network CA 2, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Locality: Sunnyvale, State/Province: California, Common Name: us01unity01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: US
Package Control: Exported certificate: Common Name: Actalis Authentication Root CA, Organization: Actalis S.p.A./03358520967, Locality: Milan, Country: IT
Package Control: Exported certificate: Locality: Sunnyvale, State/Province: California, Common Name: us01cups02.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: US
Package Control: Exported certificate: Locality: Lausanne, State/Province: VD, Common Name: ch01cups01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CH
Package Control: Exported certificate: Common Name: Buypass Class 2 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: UCA Global Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: DigiCert Trusted Root G4, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: Visa eCommerce Root, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: GTS Root R3, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: ANF Global Root CA, Serial Number: G63287510, Email Address: info@anf.es, Organizational Unit: ANF Clase 1 CA, Organization: ANF Autoridad de Certificacion, Locality: Barcelona (see current address at http://www.anf.es/es/address-direccion.html ), State/Province: Barcelona, Country: ES
Package Control: Exported certificate: Locality: Sunnyvale, State/Province: California, Common Name: USSVL-B01F01C01-CMP01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: US
Package Control: Exported certificate: Email Address: acraiz@suscerte.gob.ve, Organizational Unit: Superintendencia de Servicios de Certificacion Electronica, Organization: Sistema Nacional de Certificacion Electronica, State/Province: Distrito Capital, Locality: Caracas, Country: VE, Common Name: Autoridad de Certificacion Raiz del Estado Venezolano
Package Control: Exported certificate: Common Name: Go Daddy Root Certificate Authority - G2; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G5; Organizational Unit: (c) 2006 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: D-TRUST Root CA 3 2013, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: Global Chambersign Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: ComSign Global Root CA, Organization: ComSign Ltd., Country: IL
Package Control: Exported certificate: Locality: Suzhou, State/Province: Suzhou, Common Name: CNSUZ-B01F02C13-CMS01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CN
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions ECC RootCA 2015, Organization: Hellenic Academic and Research Institutions Cert. Authority, Locality: Athens, Country: GR
Package Control: Exported certificate: Common Name: ComSign Secured CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Locality: Suzhou, State/Province: Suzhou, Common Name: cn02cups02.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CN
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G2, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: Chambers of Commerce Root - 2008, Organization: AC Camerfirma S.A., Serial Number: A82743287, Locality: Madrid (see current address at www.camerfirma.com/address), Country: EU
Package Control: Exported certificate: Common Name: Apple Root CA - G3, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Locality: Lausanne, State/Province: VD, Common Name: CHMOR-B01FB2C01-CMS01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CH
Package Control: Exported certificate: Common Name: Staat der Nederlanden EV Root CA, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: CA Disig Root R1, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Locality: Sunnyvale, State/Province: California, Common Name: us01cups02.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: US
Package Control: Exported certificate: Locality: Lausanne, State/Province: VD, Common Name: ch01cups02.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CH
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: OpenTrust Root CA G2, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Organizational Unit: Trustis FPS Root CA, Organization: Trustis Limited, Country: GB
Package Control: Exported certificate: Common Name: Swisscom Root CA 1, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Organizational Unit: Security Communication EV RootCA1; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: Symantec Class 2 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G4; Organizational Unit: (c) 2007 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 2 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Locality: HSINCHU, State/Province: APT, Common Name: tw01unity02.logitech.com, Organizational Unit: TELECOM, Organization: LOGITECH, Country: TW
Package Control: Exported certificate: Common Name: OpenTrust Root CA G3, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Common Name: GeoTrust Global CA, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: OpenTrust Root CA G1, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Common Name: Certum Trusted Network CA, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: AAA Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Locality: Sunnyvale, State/Province: California, Common Name: us01cups02.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: US
Package Control: Exported certificate: Locality: Lausanne, State/Province: VD, Common Name: CHMOR-B01FB2C01-CMP01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CH
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Locality: Suzhou, State/Province: Suzhou, Common Name: cn02cups01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CN
Package Control: Exported certificate: Locality: Chennai, State/Province: Chennai, Common Name: INCHE-CMS01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: IN
Package Control: Exported certificate: Common Name: ApplicationCA2 Root, Organizational Unit: GPKI, Organization: Japanese Government, Country: JP
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: TRUST2408 OCES Primary CA, Organization: TRUST2408, Country: DK
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Locality: Hsinchu, State/Province: Taiwan, Common Name: TWHSC-B01F02C03-CMS01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: TW
Package Control: Exported certificate: Common Name: AffirmTrust Premium ECC, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: IdenTrust Public Sector Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Locality: Hsinchu, State/Province: Taipei, Common Name: TWHSC-B01F02C03-CMP01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: TW
Package Control: Exported certificate: Locality: Hsinchu, State/Province: Hsinchu, Common Name: tw01cups01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: TW
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 2, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: KISA RootCA 1, Organizational Unit: Korea Certification Authority Central, Organization: KISA, Country: KR
Package Control: Exported certificate: Common Name: VeriSign Class 1 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Locality: Suzhou, State/Province: Suzhou, Common Name: cn02unity01.logitech.com, Organizational Unit: Telecom, Organization: Logitech, Country: CN
Package Control: Exported certificate: Common Name: UTN - DATACorp SGC, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G2; Organizational Unit: (c) 2007 thawte, Inc. - For authorized use only; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certinomis - Autorité Racine, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: SwissSign Platinum CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R5
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G3; Organizational Unit: (c) 2008 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Organization: Government Root Certification Authority, Country: TW
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 58, in make_package_list
    packages = self.manager.list_available_packages()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 166, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache, cert_callback=print_cert_subject)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 134, in get_path
    cert_callback(Certificate.load(cert), None)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 108, in print_cert_subject
    cert.subject.human_friendly
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/asn1crypto/x509.py", line 1100, in human_friendly
    data[field_name] = type_val['value']
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/asn1crypto/core.py", line 3276, in __getitem__
    raise e
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/asn1crypto/core.py", line 3271, in __getitem__
    return self._lazy_child(key)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/asn1crypto/core.py", line 3218, in _lazy_child
    child = self.children[index] = _build(*child)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/asn1crypto/core.py", line 5144, in _build
    tag
ValueError: Error parsing Package Control.package_control.deps.asn1crypto.x509.EmailAddress - tag should have been 22, but 12 was found
    while parsing Package Control.package_control.deps.asn1crypto.x509.NameTypeAndValue
