### ISSUE TITLE
Does not work on macOS 11

### ISSUE THREAD

**Issue by dangh** [wbond/package_control#1475]
Related sources:
- https://news.ycombinator.com/item?id=23612772
- https://github.com/wbond/oscrypto/blob/master/oscrypto/_mac/_core_foundation_ctypes.py#L19

ST console logs:

```
Traceback (most recent call last):
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 274, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/bootstrap.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/dang/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
```

- Sublime Text version: build 4074
- OS version: 11.0 Beta (20A4299v)
- PackageControl version: 3.3.0

**Comment by AndrewHoos** [comment]
Looks like this might be related to the dynamic linker changes noted here:
https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes

**Comment by wbond** [comment]
Yeah - there will likely need to be some changes. Hopefully someone who has the macOS 11 beta installed can help find what changes will be necessary. It may just end up being that for the Mac shared libs we just try to open them rather than call `find_library()`.

**Comment by AndrewHoos** [comment]
Why are you not just doing `import Cocoa` etc. Using pyobjc?

**Comment by wbond** [comment]
@AndrewHoos 

 - it looks like pyobjc is not pure python, and thus it would be illogical for oscrypto to use it
 - I support Python 2.6 and 3.3 primarily (ST2 and ST3), it doesn't seem pyobjc supports either version currently
 - pyobjc is a huge dependency
 - maintaining a "distribution" of pyobjc to include with Package Control would be a ton of work

We just need to figure out what the alternative to `find_library()` in ctypes will be with Big Sur.

I don't have a macOS 11 VM and won't have time to set one up for a while, so I'm hoping an early adopter can help out.

**Comment by TheSecEng** [comment]
All system libraries now live in `/System/Library/dyld/dyld_shared_cache_x86_64`. Looking into what changes would be required to support this.

**Comment by TheSecEng** [comment]
@wbond as of right now, I think the only options are at the moment
1. Knowing the paths to the libraries you want.
2. Opening `/System/Library/dyld/dyld_shared_cache_x86_64` and going through it to identify the paths of the files you want.

Once we get the path, everything is the same.


```python

from ctypes import CDLL
core_foundation_path = "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
CoreFoundation = CDLL(core_foundation_path, use_errno=True)

```

**Comment by TheSecEng** [comment]
@dangh @wbond the supporting library [oscrypto](https://github.com/wbond/oscrypto) has been updated to support MacOS Big Sur.


@dangh Once the PR on [oscrypto](https://github.com/wbond/oscrypto) is merged, Package Control can be updated to fix this issue with the latest version of oscrypto

**Comment by max-mykhailenko** [comment]
@wbond may I know when you plan to release it?

**Comment by wbond** [comment]
No, I don’t have a date. This is a hobby for me that sits behind my day job and taking care of my family. As of right now most of my nights are spoken for this week.

**Comment by findyy99** [comment]
So, anyone know how to solve this bug on macOS big Sur? 
Are there something specific I can do?

**Comment by TheSecEng** [comment]
@findyy99 see the referenced PR above.

**Comment by findyy99** [comment]
@TheSecEng Sorry, did you mean I need to complie the `Package Control` by myself?

**Comment by TheSecEng** [comment]
I just mean that there is a PR to fix this. Will Bond just needs to test and validate it first. You can do 1 of three things.

1. Wait for a new release
2. Uninstall Package Control; Clone my fork and switch to a working branch
3. Generate a new package from my branch.

If you do either 2 or 3, you won't receive updates though. I would recommend you wait for Will to push a new release. Shouldn't be too long.

**Comment by GuruM** [comment]
Sorry if this is bad form or the wrong place to mention it, but I tried your branch and it worked for me @TheSecEng! Thanks so much.

**Comment by pak-gh** [comment]
Sorry, I new to this forum and fairly new to git. How can I get the branch mentioned about so I can get package control working with Big Sur. I really appreciate the help...

**Comment by dofy** [comment]
@pak-gh 

1. open the `Sublime` app
1. press `cmd` + `shift` + `p`
1. input `Browse Packages` and press `Enter`
1. this command will open the Finder app
1. goto the `Installed Packages` folder and delete the `Package Control` plugin file if you have
1. select the `Packages` folder which in the same level of the `Installed Packages` folder
1. `cmd` + `c` to copy the folder (path)
1. open `Terminal` app
1. input `cd ` and press `cmd` + `v`
1. you will see the command like this

    ```base
    cd /Users/USER/Library/Application Support/Sublime Text 3/Packages
    ```

1. press `Enter` to go into the folder
1. clone the @TheSecEng 's fork and checkout the `update/oscrypto` branch

    ```base
    git clone git@github.com:TheSecEng/package_control.git "Package Control"
    git checkout origin/update/oscrypto
    ```

1. restart `Sublime`

**Comment by ShawnLiii** [comment]
> git clone git@github.com:TheSecEng/package_control.git "Package Control"

Hi, thanks for mentioning. However, I met an issue when I executed this command: 
git clone git@github.com:TheSecEng/package_control.git "Package Control" 

I got the error:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dofy** [comment]
@ShawnLiii 

Oh, sorry...

Before checkout branch, you must go to the `Package Control` folder first.

**Comment by ShawnLiii** [comment]
> @ShawnLiii
> 
> Oh, sorry...
> 
> Before checkout branch, you must go to the `Package Control` folder first.

It works, thanks

**Comment by pak-gh** [comment]
I was away, just back back and saw this answer. Thanks SO MUCH.  However when I try to clone I receive the following error 
Any thoughts? 

pk@Pauls-mbpro-16 Packages % git clone git@github.com:TheSecEng/package_control.git "Package Control"
Cloning into 'Package Control'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by h-jia** [comment]
> I was away, just back back and saw this answer. Thanks SO MUCH. However when I try to clone I receive the following error
> Any thoughts?
> 
> pk@Pauls-mbpro-16 Packages % git clone [git@github.com](mailto:git@github.com):TheSecEng/package_control.git "Package Control"
> Cloning into 'Package Control'...
> Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
> [git@github.com](mailto:git@github.com): Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

You can do things below:
`
git clone https://github.com/TheSecEng/package_control
mv package_control Package\ Control
git checkout origin/update/oscrypto
`

### restart Sublime Text

**Comment by findyy99** [comment]
- Sorry, I am confusing when I open `Package Install`, It always says 

```
Error executing: /usr/bin/git symbolic-ref -q HEAD

Working directory: /Users/findyy/Library/Application Support/Sublime Text/Packages/Package Control

VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.

Sublime Text will need to be restarted once the setting is changed.

```

- What is the problem? Did I do something wrong?

**Comment by h-jia** [comment]
> * Sorry, I am confusing when I open `Package Install`, It always says
> 
> ```
> Error executing: /usr/bin/git symbolic-ref -q HEAD
> 
> Working directory: /Users/findyy/Library/Application Support/Sublime Text/Packages/Package Control
> 
> VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.
> 
> Sublime Text will need to be restarted once the setting is changed.
> ```
> 
> * What is the problem? Did I do something wrong?

You can still use it without problem. Just ignore it and install whatever package you need. Hopefully the official updates will fix all these issues very soon.

**Comment by findyy99** [comment]
@h-jia You are right! Thank you!

**Comment by pak-gh** [comment]
Thanks everyone for the awesome help!!! It's much appreciated. I receive the same error as h-jia but I'm now able to successfully install packages. Once the official build comes out I'll delete package control and reinstall it. 
This early reach has enabled me to carry on though :-)

**Comment by wbond** [comment]
This should fixed in master as of 32e44f70b6cf28f7071545a0d54b69be372f39ae.

However, please be aware I've still got some testing and merging to do before cutting a new build.

**Comment by emman-bautista** [comment]
I am having problem at the last command. It seems that branch is missing. Please help.
> 
> You can do things below:
> 
> ```
> git clone https://github.com/TheSecEng/package_control
> 
> mv package_control Package\ Control
> 
> git checkout origin/update/oscrypto
> ```

**Comment by dofy** [comment]
> I am having problem at the last command. It seems that branch is missing. Please help.
> 
> > You can do things below:
> > ```
> > git clone https://github.com/TheSecEng/package_control
> > 
> > mv package_control Package\ Control
> > 
> > git checkout origin/update/oscrypto
> > ```

You need change the directory to `Package Control` before checkout

```sh
cd Package\ Control
```

**Comment by Tekl** [comment]
It still does not work. I don't get "Package Control:" commands after installing it.

**Comment by wbond** [comment]
@Tekl If you open a new issue with the requested info, then someone can likely point you in the right direction. https://packagecontrol.io/docs/issues

**Comment by Tekl** [comment]
Thanks for the fast reply. It's the same error, so I don't think I need to open a new issue. I already tried to install Package Control manually like explained here: https://github.com/wbond/package_control/issues/1483#issuecomment-681316212

But then Sublime just thinks it is not installed.

**Comment by wbond** [comment]
This issue has been fixed on master. If you are having trouble on master, please open a new issue with the details I requested. There is a reason I asked for those details.

If you are, in fact, getting the same error as this bug report, then you are not currently running master, or did not actually follow the instructions you linked, since the original issue is from a .sublime-package, whereas installing master using the instructions you linked will result in a directory-based install.

Honestly, none of this back and forth would be necessary if you just followed the instructions I linked to and posted your entire console contents in a new issue.

**Comment by Tekl** [comment]
Sorry, I misunderstood (my English is not the best) the instructions and I did the clone inside the "Installed Packages" folder. Everything is fine now. I first thought the closed issue does mean that Sublime should install the bugfixed version.

**Comment by wbond** [comment]
After enough people test it on the beta operating system release. My hope is to have an RC in the PC prerelease channel in the next day or so.

No matter what I plan on having this in production release by the time Big Sur is ready for general consumption. For now, if someone can install a beta OS, I don't consider it onerous to clone a git repo and help test software for that beta OS.

**Comment by glgray** [comment]
> After enough people test it on the beta operating system release. My hope is to have an RC in the PC prerelease channel in the next day or so.
> 
> No matter what I plan on having this in production release by the time Big Sur is ready for general consumption. For now, if someone can install a beta OS, I don't consider it onerous to clone a git repo and help test software for that beta OS.

Thank you for the quick reply. I am not running the beta of Big Sur, but I expect it will be released any day now and I was simply checking the status of my essential software with it.

**Comment by wbond** [comment]
I believe they _just_ released beta 7, and that it is expected to be released in October, if previous years are anything to go by.

**Comment by dave4jr** [comment]
@wbond Hey Will, first off, really appreciate the extra time you spend maintaining this package, I know it's a ton of extra work. So thank you. Just wanted to shoot you a friendly reminder, Big Sur has just been released in production yesterday. Just wanted to check the status here. Thanks man.

**Comment by wbond** [comment]
Package Control 3.4.0 with Big Sur support was released at least a month ago, if I recall correctly. You’ll need to manually remove your old install, then the built in ST installer will work.

**Comment by brandonmcconnell** [comment]
For anyone who experiences this issue and needs a full up-to-date solution, here is a blend of @dofy's solution mixed with the update from @wbond about Package Control being updated to resolve this issue.

Here are the full steps to resolve this issue, essentially be deleting and reinstalling Package Control:

1. Open the Sublime Text app.
2. Press `Cmd+Shift+P`
3. Type "Browse Packages" and press Enter. This command will open the Finder app to the appropriate folder.
4. Go to the "Installed Packages" folder which is a sibling to the "Packages" folder that was opened in the previous step.
5. Delete the Package Control plugin file if you have it. It may be named something like this: `Package Control.sublime-package`
6. Restart Sublime Text (must restart via quitting `Cmd+Q` not just closing and reopening).
7. Once Sublime Text has restarted and is back up, press `Cmd+Shift+P` again.
8. Type "Install Package Control"
9. Restart Sublime Text again for good measure.
10. Press `Cmd+Shift+P`
11. Type "Package Control" — and voila, all your Package Control commands should be back 🎉

**Comment by temuraru** [comment]
The solution that worked for me was: https://github.com/wbond/package_control/issues/1577#issuecomment-940846543 "The solution is just to remove the **/usr/local/lib/libcrypto.dylib** which is broken for some reason. After removing it package control works without issues."
That file was a symlink:  /usr/local/lib/libcrypto.dylib -> ../Cellar/openssl@3/3.1.1_1/lib/libcrypto.dylib. - I'm not sure about any side-effects, though...

**Comment by deathaxe** [comment]
Not broken, but MacOS ships OpenSSL 3, but Package Control 3.x requires OpenSSL 1.1
